__author__ = "Jessika Nordin, Padraic Corcoran"
__copyright__ = "Copyright 2022"
__email__ = "jessika.nordin@scilifelab.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/guppy.smk"
include: "rules/pbmm2.smk"
include: "rules/minimap2.smk"
include: "rules/pbsv.smk"
include: "rules/sniffles.smk"


report: "report/workflow.rst"


rule all:
    input:
        compile_output_file_list,


# Add rule orders here if needed
# ruleorder:


# Add rules if needed 
# use rule * from cnv_sv as cnv_sv_*
