__author__ = "Jessika Nordin, Padraic Corcoran"
__copyright__ = "Copyright 2022"
__email__ = "jessika.nordin@scilifelab.uu.se"
__license__ = "GPL-3"

include: "rules/common.smk"
include: "rules/cpgtools.smk"
include: "rules/hifiasm.smk"
include: "rules/make_fastq.smk"
include: "rules/pbsv.smk"
include: "rules/whatshap.smk"
#include: "rules/guppy.smk"
#include: "rules/paraphase.smk"
#include: "rules/pbmm2.smk"
#include: "rules/pbsv.smk"
#include: "rules/sniffles.smk"
#include: "rules/trgt.smk"
report: "report/workflow.rst"

rule all:
    input:
        compile_output_file_list,
