---

 output: "config/output_files.json"
 resources: "config/resources.yaml"
 samples: "samples.tsv"
 units: "units.tsv"

 default_container: "docker://hydragenetics/common:0.3.0"
 
 reference:
   fasta: ""

 sniffles:
   container: "docker://hydragenetics/sniffles2:2.0.7"
   extra: "" 
   non_germline: "" #set to  --non-germline if running somatic
