---

 output: "config/output_files.json"
 resources: "config/resources.yaml"
 samples: "config/samples.tsv"
 units: "config/units.tsv"

 default_container: "docker://hydragenetics/common:0.3.0"

 pbmm2_align:
  index: reference/homo_sapiens.mmi
  preset: "HIFI"

