---

default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 6144
  mem_per_cpu: 6144
  partition: core

guppy_basecaller_gpu:
  partition: "GPU_low"
  threads: 40 
  gres: "--gres=gres:gpu:4"
  mem_mb: 770000
  mem_per_cpu: 4096

sniffles:
  mem_mb: 24576
  threads: 4
