---

 output: "config/output_files.yaml"
 resources: "config/resources.yaml"
 samples: "samples.tsv"
 units: "units.tsv"

 default_container: "docker://hydragenetics/common:0.3.0"

 basecaller: "gpu" #cpu or gpu

 guppy_basecaller_cpu:
   container: docker://genomicpariscentre/guppy:6.5.7
   configuration_file: "data/config.cfg"
   num_callers: 1
   threads_per_caller: 1

 guppy_basecaller_gpu:
   container: docker://genomicpariscentre/guppy-gpu:6.5.7
   configuration_file: "data/config.cfg"
   chunks: 20

 minimap2:
   index: data/reference.mmi

 reference:
   fasta: "data/reference.fasta"

 pbsv_discover:
   container: docker://hydragenetics/pbsv:2.9.0

 pbsv_call:
   container: docker://hydragenetics/pbsv:2.9.0
   ccs: "--ccs"

 sniffles:
   container: "docker://hydragenetics/sniffles2:2.0.7"
