files:
  - name: "_copy_pbsv_vcf"
    input: "long_read/pbsv_call/{sample}_{type}.vcf"
    output: "results/sv/{sample}_{type}.pbsv.vcf"

  - name: "_copy_sniffles_vcf"
    input: "long_read/sniffles/{sample}_{type}.vcf"
    output: "results/sv/{sample}_{type}.sniffles.vcf"

  - name: "_copy_minimap2_tsv"
    output: "result/{sample}_{type}.output.minimap2.bam"
    input: "long_read/minimap2/{sample}_{type}.bam"
    
