$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  output:
    type: string
    description: output yaml/json file defining expected output from pipeline
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container

# Entry added using Hydra-Genetics CLI - please move it into alphabetically sorted order
  pbmm2_align:
    type: object
    description: parameters for pbmm2_align
  reference:
    type: object
    description: reference used by alignment
    properties:
      fasta:
        type: string
        description: fasta reference file
      fai:
        type: string
        description: fasta reference fai file
      skip_chrs:
        type: array
        items:
            type: string
        description: list of chromosomes that should be skipped, used when determining which chr bam files will be merged

  minimap2:
    type: object
    description: parameters for minimap2
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      index:
        type: string
        description: path to minimap2 index
      sorting:
        type: string
        description: sort order of output file, coordinate or queryname, default coordinate
      sorting_extra:
        type: string
        description: extra paramters that will be forwared to samtools/picard

  pbsv_discover:
    type: object
    description: parameters for pbsv_discover
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
        
  pbsv_call:
    type: object
    description: parameters for pbsv_call
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      ccs:
        type: string
        description: add --ccs when the data is from hifi data
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
        
  sniffles:
    type: object
    description: parameters for sniffles
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded 
      non_germline:
        type: string
        description: parameter --non-germline to run somatic

required:
  - samples
  - units
  - output
  - resources
  - default_container
