$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  output:
    type: string
    description: output yaml/json file defining expected output from pipeline
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container

  minimap2:
    type: object
    description: parameters for minimap2
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      index:
        type: string
        description: path to minimap2 index
      sorting:
        type: string
        description: sort order of output file, coordinate or queryname, default coordinate
      sorting_extra:
        type: string
        description: extra paramters that will be forwared to samtools/picard
        
  reference:
    type: object
    description: reference used by alignment
    properties:
      fasta:
        type: string
        description: fasta reference file
      fai:
        type: string
        description: fasta reference fai file
      skip_chrs:
        type: array
        items:
            type: string
        description: list of chromosomes that should be skipped, used when determining which chr bam files will be merged

required:
  - samples
  - units
  - output
  - resources
  - default_container

