$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  output:
    type: string
    description: output yaml/json file defining expected output from pipeline
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container

  reference:
    type: object
    description: references
    properties:
      fasta:
        type: string
        description: human reference for mapping
    required:
      -fasta 

  pbsv_discover:
    type: object
    description: parameters for pbsv_discover
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  pbsv_call:
    type: object
    description: parameters for pbsv_call
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      ccs:
        type: string
        description: add --ccs when the data is from hifi data
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
        
  sniffles:
    type: object
    description: parameters for sniffles
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded 
      non_germline:
        type: string
        description: parameter --non-germline to run somatic

required:
  - samples
  - units
  - output
  - resources
  - default_container
