resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.3.0"

pbsv_discover:
  container: docker://hydragenetics/pbsv:2.9.0

pbsv_call:
  container: docker://hydragenetics/pbsv:2.9.0 
